export const TEMP_CONTACT_DATA = [
  {
    id: "1",
    name: "Julia Nowak",
    prefix: "+48",
    phone: "123456789",
    picture: "https://randomuser.me/api/portraits/med/women/10.jpg",
  },
  {
    id: "2",
    name: "Liam O'Sullivan",
    prefix: "+353",
    phone: "876543210",
    picture: "https://randomuser.me/api/portraits/med/men/15.jpg",
  },
  {
    id: "3",
    name: "Sofia García",
    prefix: "+34",
    phone: "612345678",
    picture: "https://randomuser.me/api/portraits/med/women/23.jpg",
  },
  {
    id: "4",
    name: "Kenji Tanaka",
    prefix: "+81",
    phone: "801234567",
    picture: "https://randomuser.me/api/portraits/med/men/29.jpg",
  },
  {
    id: "5",
    name: "Amélie Dubois",
    prefix: "+33",
    phone: "712345678",
    picture: "https://randomuser.me/api/portraits/med/women/35.jpg",
  },
  {
    id: "6",
    name: "Ethan Smith",
    prefix: "+1",
    phone: "2025550143",
    picture: "https://randomuser.me/api/portraits/med/men/42.jpg",
  },
  {
    id: "7",
    name: "Fatima Al-Fulan",
    prefix: "+966",
    phone: "501234567",
    picture: "https://randomuser.me/api/portraits/med/women/47.jpg",
  },
  {
    id: "8",
    name: "Carlos Pereira",
    prefix: "+55",
    phone: "21987654321",
    picture: "https://randomuser.me/api/portraits/med/men/52.jpg",
  },
  {
    id: "9",
    name: "Chloe Wilson",
    prefix: "+61",
    phone: "412345678",
    picture: "https://randomuser.me/api/portraits/med/women/63.jpg",
  },
  {
    id: "10",
    name: "Hans Müller",
    prefix: "+49",
    phone: "15123456789",
    picture: "https://randomuser.me/api/portraits/med/men/70.jpg",
  },
];
